spring:
  application:
    name: giant
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jackson:
    time-zone: UTC
  profiles:
    active: local

server:
  port: 8080