CREATE SCHEMA "auth";

CREATE SCHEMA "employee";

CREATE TYPE "auth"."auth_role" AS ENUM ('USER', 'ADMIN', 'LEFT');

CREATE TYPE "employee"."employee_role" AS ENUM ('DEPARTMENT_CHIEF', 'TEAM_CHIEF', 'EMPLOYEE', 'LEFT');

CREATE TABLE "auth"."account"
(
    "id"            bigint GENERATED BY DEFAULT AS IDENTITY,
    "user_name"     varchar(25),
    "password_hash" varchar(255),
    "phone_number"  varchar(15),
    "email"         varchar(255),
    "auth_role"     "auth"."auth_role"          NOT NULL,
    "created_at"    timestamp(6) with time zone NOT NULL,
    "updated_at"    timestamp(6) with time zone NOT NULL,
    "deleted_at"    timestamp(6) with time zone,
    CONSTRAINT "pk_account" PRIMARY KEY ("id"),
    CONSTRAINT "ck_user_deleted_state" CHECK ((
        ("auth"."account"."auth_role" <> 'LEFT' AND "auth"."account"."deleted_at" IS NULL)
            OR
        ("auth"."account"."auth_role" = 'LEFT' AND "auth"."account"."deleted_at" IS NOT NULL)
        ))
);

CREATE TABLE "auth"."refresh_token"
(
    "id"         bigint GENERATED BY DEFAULT AS IDENTITY,
    "account_id" bigint                      NOT NULL,
    "token"      varchar(255)                NOT NULL,
    "expires_at" timestamp(6) with time zone NOT NULL,
    CONSTRAINT "pk_refresh_token" PRIMARY KEY ("id"),
    CONSTRAINT "uq_active_refresh_token" UNIQUE ("token")
);
ALTER TABLE "auth"."refresh_token"
    ADD CONSTRAINT "fk_refresh_token_user" FOREIGN KEY ("account_id") REFERENCES "auth"."account" ("id") ON DELETE cascade ON UPDATE cascade;

CREATE TABLE "employee"."department"
(
    "id"              bigint GENERATED BY DEFAULT AS IDENTITY,
    "department_code" varchar(255) NOT NULL,
    "department_name" varchar(255) NOT NULL,
    CONSTRAINT "pk_department" PRIMARY KEY ("id"),
    CONSTRAINT "uq_department_code" UNIQUE ("department_code"),
    CONSTRAINT "uq_department_department_name" UNIQUE ("department_name")
);

CREATE TABLE "employee"."position"
(
    "id"               bigint GENERATED BY DEFAULT AS IDENTITY,
    "position_code"    varchar(255) NOT NULL,
    "position_name"    varchar(255) NOT NULL,
    "basic_salary"     bigint       NOT NULL,
    "incentive_salary" bigint       NOT NULL,
    CONSTRAINT "pk_position" PRIMARY KEY ("id"),
    CONSTRAINT "uq_position_code" UNIQUE ("position_code"),
    CONSTRAINT "uq_position_position_name" UNIQUE ("position_name")
);

CREATE TABLE "employee"."team"
(
    "id"            bigint GENERATED BY DEFAULT AS IDENTITY,
    "team_code"     varchar(255) NOT NULL,
    "department_id" bigint       NOT NULL,
    "team_name"     varchar(255) NOT NULL,
    CONSTRAINT "pk_team" PRIMARY KEY ("id"),
    CONSTRAINT "uq_team_code" UNIQUE ("team_code"),
    CONSTRAINT "uq_team_team_name" UNIQUE ("team_name")
);
ALTER TABLE "employee"."team"
    ADD CONSTRAINT "fk_team_department" FOREIGN KEY ("department_id") REFERENCES "employee"."department" ("id") ON DELETE cascade ON UPDATE cascade;

CREATE TABLE "employee"."profile"
(
    "id"            bigint                      NOT NULL,
    "employee_code" varchar(255)                NOT NULL,
    "employee_name" varchar(255)                NOT NULL,
    "team_id"       bigint                      NOT NULL,
    "employee_role" "employee"."employee_role"  NOT NULL,
    "position_id"   bigint                      NOT NULL,
    "created_by"    bigint                      NOT NULL,
    "updated_by"    bigint                      NOT NULL,
    "created_at"    timestamp(6) with time zone NOT NULL,
    "updated_at"    timestamp(6) with time zone NOT NULL,
    "left_at"       timestamp(6) with time zone,
    CONSTRAINT "pk_profile" PRIMARY KEY ("id"),
    CONSTRAINT "uq_employee_code" UNIQUE ("employee_code"),
    CONSTRAINT "ck_employee_left_state" CHECK ((
        ("employee"."profile"."employee_role" <> 'LEFT' AND "employee"."profile"."left_at" IS NULL)
            OR
        ("employee"."profile"."employee_role" = 'LEFT' AND "employee"."profile"."left_at" IS NOT NULL)
        ))
);
ALTER TABLE "employee"."profile"
    ADD CONSTRAINT "fk_profile_account" FOREIGN KEY ("id") REFERENCES "auth"."account" ("id") ON DELETE cascade ON UPDATE cascade;
ALTER TABLE "employee"."profile"
    ADD CONSTRAINT "fk_profile_team" FOREIGN KEY ("team_id") REFERENCES "employee"."team" ("id") ON DELETE cascade ON UPDATE cascade;
ALTER TABLE "employee"."profile"
    ADD CONSTRAINT "fk_position" FOREIGN KEY ("position_id") REFERENCES "employee"."position" ("id") ON DELETE cascade ON UPDATE cascade;


CREATE TABLE "employee"."serial"
(
    "id"           bigint GENERATED BY DEFAULT AS IDENTITY,
    "serial_name"  varchar(255) NOT NULL,
    "serial_value" varchar(255) NOT NULL,
    CONSTRAINT "pk_serial" PRIMARY KEY ("id"),
    CONSTRAINT "uq_serial_name" UNIQUE ("serial_name")
);

CREATE VIEW "employee"."employee_profile_view" AS
(
select "ep"."id",
       "ep"."employee_code",
       "ep"."employee_name",
       "ep"."employee_role",
       "epn"."position_code",
       "epn"."position_name",
       "ed"."department_code",
       "ed"."department_name",
       "et"."team_code",
       "et"."team_name",
       "au"."phone_number",
       "au"."email",
       "epc"."employee_name" as "created_employee_name",
       "epu"."employee_name" as "updated_employee_name",
       "ep"."created_at",
       "ep"."updated_at",
       "ep"."left_at"
from "employee"."profile" "ep"
         inner join "auth"."account" "au"
                    on "au"."id" = "ep"."id"
         left join "employee"."position" "epn"
                   on "epn"."id" = "ep"."position_id"
         left join "employee"."team" "et"
                   on "et"."id" = "ep"."team_id"
         left join "employee"."department" "ed"
                   on "ed"."id" = "et"."department_id"
         left join "employee"."profile" "epc"
                   on "epc"."id" = "ep"."created_by"
         left join "employee"."profile" "epu"
                   on "epu"."id" = "ep"."updated_by"
    );

CREATE VIEW "auth"."auth_view" AS
(
select "au"."id",
       "au"."password_hash",
       "au"."user_name",
       "au"."auth_role",
       "au"."phone_number",
       "au"."email",
       "ep"."employee_code",
       "ep"."employee_name",
       "ep"."employee_role",
       "epn"."position_code",
       "epn"."position_name",
       "ed"."department_code",
       "ed"."department_name",
       "et"."team_code",
       "et"."team_name"
from "auth"."account" "au"
         inner join "employee"."profile" "ep" on "au"."id" = "ep"."id"
         inner join "employee"."position" "epn" on "ep"."position_id" = "epn"."id"
         inner join "employee"."team" "et" on "ep"."team_id" = "et"."id"
         inner join "employee"."department" "ed" on "et"."department_id" = "ed"."id"
where "au"."auth_role" <> 'LEFT');